
#create a folder for components data ingestion, 
#data validation,data transformation,
# model training ,model evaluation

artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/atharvasamel/End-to-End-MLProject-using-MLflow-and-EC2-Insance/raw/main/winequality-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib

model_evaluation:
  root_dir : artifacts/model_evaluation
  test_data_path : artifacts/data_transformation/test.csv
  model_path : artifacts/model_trainer/model.joblib
  metric_file_name : artifacts/model_evaluation/metrics.json