
#create a folder for components data ingestion, 
#data validation,data transformation,
# model training ,model evaluation

artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/atharvasamel/End-to-End-MLProject-using-MLflow-and-EC2-Insance/raw/main/winequality-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion